apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-cert-production
  namespace: default
spec:
  commonName: api.dev.quarq.ai
  secretName: traefik-cert-prod
  dnsNames:
    - api.dev.quarq.ai
  issuerRef:
    kind: Issuer
    name: letsencrypt-production
